name: coopah_weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  fonts:
    - family: Futura Condensed PT
      fonts:
        - asset: assets/fonts/futura-condensed/futura-pt-bold-589e44b6aacd3.otf
          weight: 800
    - family: Circular Std
      fonts:
        - asset: assets/fonts/circular-std/CircularStd-Book.ttf
          weight: 400
